# Generated by Django 3.2.dev20200521103454 on 2020-06-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='LastName',
        ),
    ]
