# Generated by Django 3.2.dev20200521103454 on 2020-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0002_auto_20200618_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(help_text='Enter the first name', max_length=100)),
                ('CountryPhone', models.CharField(help_text='Enter the last name', max_length=100)),
                ('TwilloSid', models.CharField(help_text='Enter the country', max_length=100)),
                ('TwilloKey', models.IntegerField(help_text='Enter the phone number')),
                ('Email', models.EmailField(help_text='Enter email address', max_length=100)),
            ],
            options={
                'verbose_name': 'Twllo',
                'verbose_name_plural': 'Twillo Accounts',
            },
        ),
    ]
