# Generated by Django 3.2.dev20200521103454 on 2020-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0003_twillo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(help_text='Enter the first name', max_length=100)),
                ('Status', models.CharField(help_text='Enter the last name', max_length=100)),
            ],
            options={
                'verbose_name': 'Server Status',
                'verbose_name_plural': 'Servers Status',
            },
        ),
        migrations.AlterField(
            model_name='twillo',
            name='AccountName',
            field=models.CharField(help_text='Enter Twilio Account Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='twillo',
            name='CountryPhone',
            field=models.CharField(help_text='Enter the Account Phone Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='twillo',
            name='TwilloKey',
            field=models.IntegerField(help_text='Enter the Twillio Key'),
        ),
        migrations.AlterField(
            model_name='twillo',
            name='TwilloSid',
            field=models.CharField(help_text='Enter the Twilio SID', max_length=100),
        ),
    ]
