# Generated by Django 3.2.dev20200521103454 on 2020-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0004_auto_20200618_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='Status',
            field=models.CharField(choices=[('b', 'Banned'), ('f', 'Offline'), ('o', 'Online')], max_length=1),
        ),
    ]
