# Generated by Django 3.2.dev20200521103454 on 2020-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0005_auto_20200618_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='twillo',
            name='Status',
            field=models.CharField(choices=[('a', 'Active'), ('b', 'Banned')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('r', 'Ready to Send'), ('d', 'Done')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
