# Generated by Django 3.0.7 on 2020-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTech', '0007_auto_20200618_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twillo',
            name='Status',
            field=models.CharField(choices=[('a', 'Active'), ('b', 'Banned'), ('i', 'Inactive')], max_length=1),
        ),
    ]
